# RCS SQL Intro

# SQL - Structured Query Language
Domain-specific language used in programming and designed for managing data held in a relational database management system (RDBMS)

# History
* Set Theory
* Edgar F. Cobb Relation Model 1970 (later https://en.wikipedia.org/wiki/Codd%27s_12_rules)
* Normalforms (Informally, a relational database relation is often described as "normalized" if it meets third normal form. Most 3NF relations are free of insertion, update, and deletion anomalies.)
* ACID (Atomicity, Consistency, Isolation, Durability) 
* Future




* CREATE
* INSERT
* UPDATE
* DELETE

* SELECT

(In general programming CRUD (Create,Read,Update,Delete))

# SQL Lite - Embedded SQL Database
###  https://www.sqlite.org/index.html
![SQL](https://www.sqlite.org/images/sqlite370_banner.gif)

* simple single user DB adhering to SQL standard
* up to 140TB in a single file

## SQLite vs other SQL databases (MySQL, Postegres, Oracle, Microsoft SQL server)
https://www.sqlite.org/whentouse.html

* https://www.mysql.com/ (Bought by Oracle, but still open source)
* MySQL fork: https://mariadb.org/
* https://www.postgresql.org/
* https://www.microsoft.com/en-us/sql-server

In [ ]:
## Resources / books / tutorials / online viewers

### Books


 * https://www.amazon.com/Learning-SQL-Master-Fundamentals/dp/0596520832
 * https://www.amazon.com/Head-First-SQL-Brain-Learners/dp/0596526849
 * For manga lovers: https://www.amazon.com/Manga-Guide-Databases-Mana-Takahashi/dp/1593271905
 
Online
 * https://sqliteonline.com/

 * https://www.python-course.eu/sql_python.php      
 * [SchemaCrawler](https://www.schemacrawler.com/diagramming.html) - for crawling db schemas lot of yak shaving involved
 * https://sqlzoo.net/ - great practice tool

In [ ]:
# Many ways to use SQL (command line, varius GUIs) ORM
# we'll use it embedded in Python

In [8]:
import sqlite3

In [11]:
db = sqlite3.connect('./db/chinook.db')

In [12]:
# prepare a cursor object using cursor() method
cursor = db.cursor()

In [28]:
# sample database Chinook
# fork at https://github.com/ValRCS/chinook-database
# good tutorials at http://www.sqlitetutorial.net/sqlite-python/

![CHINOOK STRUCTURE](sqlite-sample-database-color.jpg)

In [ ]:
# Open question on easiest way to visualize table schema: https://stackoverflow.com/questions/433071/good-tool-to-visualise-database-schema

## Chinook sample database tables
### There are 11 tables in the chinook sample database

*  employees table stores employees data such as employee id, last name, first name, etc. It also has a field named ReportsTo to specify who reports to whom.
*  customers table stores customers data.
*  invoices & invoice_items tables: these two tables store invoice data. The invoices table stores invoice header data and the invoice_items table stores the invoice line items data.
*  artists table stores artists data. It is a simple table that contains only artist id and name.
*  albums table stores data about a list of tracks. Each album belongs to one artist. However, one artist may have multiple albums.
*  media_types table stores media types such as MPEG audio file, ACC audio file, etc.
*  genres table stores music types such as rock, jazz, metal, etc.
*  tracks table store the data of songs. Each track belongs to one album.
*  playlists & playlist_track tables: playlists table store data about playlists. Each playlist contains a list of tracks. Each track may belong to multiple playlists. The relationship between the playlists table and tracks table is many-to-many. The playlist_track table is used to reflect this relationship.

### SELECT DISTINCT column_list

### FROM table_list

###   JOIN table ON join_condition
  
### WHERE row_filter

### ORDER BY column

### LIMIT count OFFSET offset

### GROUP BY column

### HAVING group_filter

* Use ORDER BY clause to sort the result set
* Use DISTINCT clause to query unique rows in a table
* Use WHERE clause to filter rows in the result set
* Use LIMIT OFFSET clauses to constrain the number of rows returned
* Use INNER JOIN or LEFT JOIN to query data from multiple tables using join.
* Use GROUP BY to get the group rows into groups and apply aggregate function for each group.
* Use HAVING clause to filter groups

In [14]:
cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
print(cursor.fetchall())

[('albums',), ('sqlite_sequence',), ('artists',), ('customers',), ('employees',), ('genres',), ('invoices',), ('invoice_items',), ('media_types',), ('playlists',), ('playlist_track',), ('tracks',), ('sqlite_stat1',)]

In [16]:
import pandas as pd

In [29]:
# most popular type of query!
table = pd.read_sql_query("SELECT * from albums", db)

In [20]:
table

     AlbumId                                              Title  ArtistId
0          1              For Those About To Rock We Salute You         1
1          2                                  Balls to the Wall         2
2          3                                  Restless and Wild         2
3          4                                  Let There Be Rock         1
4          5                                           Big Ones         3
5          6                                 Jagged Little Pill         4
6          7                                           Facelift         5
7          8                                     Warner 25 Anos         6
8          9                     Plays Metallica By Four Cellos         7
9         10                                         Audioslave         8
10        11                                       Out Of Exile         8
11        12                                BackBeat Soundtrack         9
12        13                           The Best Of Billy Cobham        10
13        14           Alcohol Fueled Brewtality Live! [Disc 1]        11
14        15           Alcohol Fueled Brewtality Live! [Disc 2]        11
15        16                                      Black Sabbath        12
16        17                    Black Sabbath Vol. 4 (Remaster)        12
17        18                                         Body Count        13
18        19                                   Chemical Wedding        14
19        20   The Best Of Buddy Guy - The Millenium Collection        15
20        21                                       Prenda Minha        16
21        22                              Sozinho Remix Ao Vivo        16
22        23                                     Minha Historia        17
23        24                                     Afrociberdelia        18
24        25                                    Da Lama Ao Caos        18
25        26                                Acústico MTV [Live]        19
26        27                                Cidade Negra - Hits        19
27        28                                           Na Pista        20
28        29                                     Axé Bahia 2001        21
29        30                       BBC Sessions [Disc 1] [Live]        22
..       ...                                                ...       ...
317      318                           SCRIABIN: Vers la flamme       250
318      319  Armada: Music from the Courts of England and S...       251
319      320                    Mozart: Symphonies Nos. 40 & 41       248
320      321                                      Back to Black       252
321      322                                              Frank       252
322      323              Carried to Dust (Bonus Track Version)       253
323      324          Beethoven: Symphony No. 6 'Pastoral' Etc.       254
324      325                   Bartok: Violin & Viola Concertos       255
325      326             Mendelssohn: A Midsummer Night's Dream       256
326      327                 Bach: Orchestral Suites Nos. 1 - 4       257
327      328      Charpentier: Divertissements, Airs & Concerts       258
328      329                             South American Getaway       259
329      330                            Górecki: Symphony No. 3       260
330      331                           Purcell: The Fairy Queen       261
331      332                      The Ultimate Relexation Album       262
332      333                  Purcell: Music for the Queen Mary       263
333      334                       Weill: The Seven Deadly Sins       264
334      335  J.S. Bach: Chaconne, Suite in E Minor, Partita...       265
335      336  Prokofiev: Symphony No.5 & Stravinksy: Le Sacr...       248
336      337                   Szymanowski: Piano Works, Vol. 1       266
337      338                        Nielsen: The Six Symphonies       267
338      339  Great Recordings of the Century: Paganini's 24...       268
339      340        Liszt - 12 Études D'Execution Transcendante       269
340      341  Great Recordings of the Century - Shubert: Sch...       270
341      342  Locatelli: Concertos for Violin, Strings and C...       271
342      343                             Respighi:Pines of Rome       226
343      344  Schubert: The Late String Quartets & String Qu...       272
344      345                                Monteverdi: L'Orfeo       273
345      346                              Mozart: Chamber Music       274
346      347  Koyaanisqatsi (Soundtrack from the Motion Pict...       275

[347 rows x 3 columns]

In [21]:
tracks = pd.read_sql_query("""
    SELECT trackid,
        name,
         composer,
         unitprice
    FROM
     tracks;
    """, db)

In [22]:
tracks.head()

,TrackId,Name,Composer,UnitPrice
0,1,For Those About To Rock (We Salute You),"Angus Young, Malcolm Young, Brian Johnson",0.99
1,2,Balls to the Wall,None,0.99
2,3,Fast As a Shark,"F. Baltes, S. Kaufman, U. Dirkscneider & W. Ho...",0.99
3,4,Restless and Wild,"F. Baltes, R.A. Smith-Diesel, S. Kaufman, U. D...",0.99
4,5,Princess of the Dawn,Deaffy & R.A. Smith-Diesel,0.99

In [ ]:
# Exercise !
# Create full tables for playlists and customers

In [31]:
tracklen = pd.read_sql_query("""
    SELECT
     name,
     milliseconds, 
     albumid
    FROM
     tracks
    ORDER BY
     milliseconds DESC;
    """, db)
tracklen.head()

                          Name  Milliseconds  AlbumId
0       Occupation / Precipice       5286953      227
1      Through a Looking Glass       5088838      229
2  Greetings from Earth, Pt. 1       2960293      253
3      The Man With Nine Lives       2956998      253
4  Battlestar Galactica, Pt. 2       2956081      253

In [34]:
alltracks = pd.read_sql_query("""
    SELECT
     trackid,
     name,
     title
    FROM
     tracks
    INNER JOIN albums ON albums.albumid = tracks.albumid;
    INNER JOIN albums ON albums.albumid = tracks.albumid;
    """, db)
alltracks.tail()

,TrackId,Name,Title
3498,3499,Pini Di Roma (Pinien Von Rom) \ I Pini Della V...,Respighi:Pines of Rome
3499,3500,"String Quartet No. 12 in C Minor, D. 703 ""Quar...",Schubert: The Late String Quartets & String Qu...
3500,3501,"L'orfeo, Act 3, Sinfonia (Orchestra)",Monteverdi: L'Orfeo
3501,3502,"Quintet for Horn, Violin, 2 Violas, and Cello ...",Mozart: Chamber Music
3502,3503,Koyaanisqatsi,Koyaanisqatsi (Soundtrack from the Motion Pict...

In [38]:
tracksart = pd.read_sql_query("""
    SELECT
     trackid,
     tracks.name AS TRACK,
     title,
     artists.name AS ARTIST
    FROM
     tracks
    INNER JOIN albums ON albums.albumid = tracks.albumid
    INNER JOIN artists ON albums.artistid = artists.artistid;
    """, db)
tracksart.tail()

,TrackId,TRACK,Title,ARTIST
3498,3499,Pini Di Roma (Pinien Von Rom) \ I Pini Della V...,Respighi:Pines of Rome,Eugene Ormandy
3499,3500,"String Quartet No. 12 in C Minor, D. 703 ""Quar...",Schubert: The Late String Quartets & String Qu...,Emerson String Quartet
3500,3501,"L'orfeo, Act 3, Sinfonia (Orchestra)",Monteverdi: L'Orfeo,"C. Monteverdi, Nigel Rogers - Chiaroscuro; Lon..."
3501,3502,"Quintet for Horn, Violin, 2 Violas, and Cello ...",Mozart: Chamber Music,Nash Ensemble
3502,3503,Koyaanisqatsi,Koyaanisqatsi (Soundtrack from the Motion Pict...,Philip Glass Ensemble

In [39]:
# Exercise add Track length to our query